### ISSUE TITLE
[Feature Request]Add a Search playlist feature

### ISSUE THREAD

**Issue by twishasaraiya** [udiboy1209/fast_playlist#23]
I think there should be a search bar to search from the playlist. Can I work on it ???

**Comment by udiboy1209** [comment]
That would be a nice feature! Before you jump into the implementation though, can you think about how the UX would be like? Adding a different search bar solely for searching in playlist is kinda pointless. Maybe the current search bar should show results from playlist, as well as youtube results.

**Comment by twishasaraiya** [comment]
It could be like that when we search the drop-down section could have two columns one to show from a playlist and other from youtube. Something like this [https://dribbble.com/shots/2550053-Searching](url)

**Comment by udiboy1209** [comment]
Two columns makes sense when you have two different items, like in the example you have added tracks,playlists and users are in three different columns. Because we just want to search songs, two sections on top of each other would be better. The top section could be for songs from playlist and could be hidden when there is no match.

You also need to consider how user will interact with the searched song. Will clicking on it play the song, or will it simply scroll to that position in the playlist?

**Comment by twishasaraiya** [comment]
Ok. Can you tell me how can I access the playlist array in search.js????

**Comment by udiboy1209** [comment]
The `playlist` variable in search.js is a reference to the playlist.js module object. You should read about workings of require.js in case you want to know details. The relevant part for you is running a `for` loop on `playlist.size()` and using `playlist.get(i)` to get the data of i<sup>th</sup> song in the playlist.

**Comment by aniketgattani** [comment]
can i work on this issue if nobody else is working

**Comment by udiboy1209** [comment]
@twishasaraiya had started an implementation I guess. If she isn't working on it, you can pick it up @aniketgattani

**Comment by twishasaraiya** [comment]
I have already started working on it but due to my exams, I have not been able to complete it. I almost done with it. I will soon be asking for a review.

**Comment by udiboy1209** [comment]
@twishasaraiya take your time. @aniketgattani you can find another feature to contribute to in the README!
