### ISSUE TITLE
Copy Share Link button does not work on Mac

### ISSUE THREAD

**Issue by atisayajain** [udiboy1209/fast_playlist#27]
Copy Share Link button to share playlist does not work on Mac environment (OS X High Sierra).
Tested on Safari and Chrome. Neither the popup shows up nor the link is getting copied.

**Comment by udiboy1209** [comment]
Confirmed not working on Linux too. I think there is a bug in `main.js`. The console shows this error:

```
ReferenceError: playing is not defined[Learn More] main.js:110:1
```

**Comment by atisayajain** [comment]
Share Link button works well in stable version but does not work in beta version. Should we go back to the same code?
`ReferenceError` is for a not defined variable being used which is defined in the stable version.

**Comment by udiboy1209** [comment]
I think this bug was introduced in #15, where the reference to `playing` wasn't updated properly. Instead of reverting back to the stable branch, try and fix the error.

The reference to `playing` should be updated to be fetched from `player` module in [this function](https://github.com/udiboy1209/fast_playlist/blob/master/js/main.js#L105). It's an easy fix. You may need to add a `getPlaying()` function in `player.js`

**Comment by atisayajain** [comment]
Share link is being copied now and popup is also being show. Another bug is being experienced now due to which the playlist on the copied link turns empty. It is apparently due to `playlist.js`:

`Uncaught TypeError: Cannot read property 'videos' of null
    at setup (playlist.js:12)
`

Should I submit the PR with just fix for copying link and raise another issue for the new bug?

**Comment by udiboy1209** [comment]
These bugs are related right? No need to create a new issue, fix them both in the same PR

**Comment by atisayajain** [comment]
Please review the PR #31 and let me know if any changes have to be made.

**Comment by udiboy1209** [comment]
#32 closes this
